[package]
name = "rasterization-in-a-weekend-rs"
version = "0.1.0"
authors = ["Danny Fritz <dannyfritz@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra-glm = "0.2.1"
obj = "0.9.0"

[dependencies.image]
version = "0.21.0"
default-features = false
features = ["png_codec"]
